### ISSUE TITLE
Connection closed before full header was received

### ISSUE THREAD

**Issue by droplet-js** [dart-lang/pub_server#33]

**Comment by jonasfj** [comment]
Please explain what you are trying to do? What platform are you on? Are you using the [Chinese community mirror](https://flutter.dev/community/china)..

Please reopen if you have additional information...

Note. the pub server is https://github.com/dart-lang/pub-dartlang-dart
This repo is an abstraction defining the interface...

**Comment by droplet-js** [comment]
@jonasfj 

Dockerfile
````
# --- download ---

FROM alpine:3.8 as download

RUN wget https://github.com/dart-lang/pub_server/archive/master.tar.gz
RUN tar xzf master.tar.gz

# --- prod ---

FROM google/dart:2.2.0

MAINTAINER v7lin <v7lin@qq.com>

COPY --from=download /pub_server-master /pub_server

WORKDIR /pub_server

RUN pub get

EXPOSE 8080

ENTRYPOINT ["/usr/bin/dart", "example/example.dart", "-d", "/tmp/package-db"]
````

docker-compose.yml
````
version: "3.7"

services:

  pub_server:
    container_name: pub_server
    image: v7lin/pub_server
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ../../dev-ops-repo/pub_server:/tmp/package-db
    environment:
      - TZ=${TIME_ZONE:-Asia/Shanghai}
````

i want to run pub_server on docker container. and publish dart packages to private pub_server
````
pub publish --server http://localhost:8080
````
